phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install awscli

  pre_build:
    commands:
      - echo "Installing dependencies"
  
  build:
    commands:
      - echo "Starting S3 sync"
      - aws s3 sync public s3://os-musics.com-public/public --delete
      - echo "S3 sync completed"
